-- Seed data for meal_library table
-- Covers: Indian, South Indian, North Indian, Chinese, Italian, Mexican, Mediterranean, Japanese, Korean, Thai, American, Middle Eastern
-- Food types: Dish, Snack, Beverage, Dessert
-- Health tags: High Protein, Weight Loss, Diabetic Friendly, Heart Healthy, Low Carb

-- NORTH INDIAN DISHES
INSERT INTO public.meal_library (name, cuisine, food_type, health_tags, image_url, original_nutrition, improved_nutrition, changes, swaps, cooking_method, portion_tip) VALUES
('Grilled Tandoori Chicken', 'North Indian', 'Dish', ARRAY['High Protein','Weight Loss'], 'https://images.unsplash.com/photo-1735353783227-80b22ef618d9?w=800', '{"name":"Butter Chicken","calories":820,"protein":32,"carbs":28,"fat":56,"fiber":3,"sugar":8}', '{"name":"Grilled Tandoori Chicken","calories":480,"protein":42,"carbs":12,"fat":18,"fiber":4,"sugar":3}', '[{"label":"Calories","change":"down","percentage":41},{"label":"Fat","change":"down","percentage":68},{"label":"Protein","change":"up","percentage":31}]', '[{"original":"Heavy cream","replacement":"Greek yogurt","benefit":"60% less fat + probiotics"},{"original":"Butter","replacement":"Olive oil spray","benefit":"90% less saturated fat"},{"original":"Deep frying","replacement":"Tandoor grilling","benefit":"Charred flavor without oil"}]', '{"original":"Deep fried in butter","improved":"Tandoor grilled","benefit":"Removes excess oil while adding smoky flavor"}', 'Serve with a side salad instead of naan for extra fiber'),

('Paneer Tikka Bowl', 'North Indian', 'Dish', ARRAY['High Protein','Heart Healthy'], 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800', '{"name":"Paneer Butter Masala","calories":920,"protein":28,"carbs":32,"fat":68,"fiber":2,"sugar":10}', '{"name":"Paneer Tikka Bowl","calories":540,"protein":32,"carbs":22,"fat":28,"fiber":6,"sugar":4}', '[{"label":"Calories","change":"down","percentage":41},{"label":"Fat","change":"down","percentage":59},{"label":"Fiber","change":"up","percentage":200}]', '[{"original":"Heavy cream gravy","replacement":"Yogurt marinade","benefit":"70% less fat"},{"original":"White rice","replacement":"Quinoa","benefit":"More protein and fiber"},{"original":"Butter","replacement":"Mustard oil","benefit":"Heart-healthy fats"}]', '{"original":"Pan fried in butter","improved":"Oven grilled","benefit":"Crispy texture without excess oil"}', 'Use 100g paneer per serving, pair with mint chutney'),

('Brown Rice Biryani', 'North Indian', 'Dish', ARRAY['High Protein','Heart Healthy'], 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800', '{"name":"Chicken Biryani","calories":850,"protein":30,"carbs":95,"fat":35,"fiber":3,"sugar":5}', '{"name":"Brown Rice Biryani","calories":520,"protein":38,"carbs":58,"fat":14,"fiber":8,"sugar":3}', '[{"label":"Calories","change":"down","percentage":39},{"label":"Fiber","change":"up","percentage":167},{"label":"Fat","change":"down","percentage":60}]', '[{"original":"White basmati rice","replacement":"Brown basmati rice","benefit":"3x more fiber"},{"original":"Ghee","replacement":"Cold-pressed coconut oil","benefit":"Medium-chain fatty acids"},{"original":"Fried onions","replacement":"Caramelized onions","benefit":"No added oil"}]', '{"original":"Dum cooking with ghee","improved":"Pressure cooked with minimal oil","benefit":"Retains nutrients, uses less fat"}', 'One cup cooked rice per serving is plenty'),

('Baked Samosas', 'North Indian', 'Snack', ARRAY['Weight Loss','Diabetic Friendly'], 'https://images.unsplash.com/photo-1626132647523-66f2bf18ba8c?w=800', '{"name":"Fried Samosas","calories":720,"protein":12,"carbs":68,"fat":44,"fiber":4,"sugar":3}', '{"name":"Baked Whole Wheat Samosas","calories":380,"protein":18,"carbs":42,"fat":14,"fiber":8,"sugar":2}', '[{"label":"Calories","change":"down","percentage":47},{"label":"Fat","change":"down","percentage":68},{"label":"Fiber","change":"up","percentage":100}]', '[{"original":"Maida (refined flour)","replacement":"Whole wheat flour","benefit":"More fiber, lower GI"},{"original":"Deep frying","replacement":"Air baking","benefit":"80% less oil"},{"original":"Potato filling","replacement":"Mixed veggie + paneer","benefit":"More protein"}]', '{"original":"Deep fried","improved":"Oven baked at 200°C","benefit":"Crispy without oil absorption"}', 'Serve 2-3 pieces with green chutney'),

-- SOUTH INDIAN DISHES
('Oats Ragi Dosa', 'South Indian', 'Dish', ARRAY['High Protein','Weight Loss','Diabetic Friendly'], 'https://images.unsplash.com/photo-1694170269221-ea3df8c27f87?w=800', '{"name":"Masala Dosa","calories":620,"protein":10,"carbs":82,"fat":28,"fiber":3,"sugar":4}', '{"name":"Oats and Ragi Dosa","calories":380,"protein":24,"carbs":48,"fat":10,"fiber":9,"sugar":2}', '[{"label":"Calories","change":"down","percentage":39},{"label":"Protein","change":"up","percentage":140},{"label":"Fiber","change":"up","percentage":200}]', '[{"original":"White rice batter","replacement":"Ragi + oats batter","benefit":"Higher protein and calcium"},{"original":"Ghee on griddle","replacement":"Non-stick spray","benefit":"90% less fat"},{"original":"Potato filling","replacement":"Sprouts filling","benefit":"3x more protein"}]', '{"original":"Griddle with ghee","improved":"Non-stick griddle","benefit":"Minimal oil needed"}', 'Pair with sambar for a complete protein meal'),

('Millet Idli', 'South Indian', 'Snack', ARRAY['Heart Healthy','Diabetic Friendly'], 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800', '{"name":"Regular Idli","calories":340,"protein":8,"carbs":62,"fat":4,"fiber":2,"sugar":2}', '{"name":"Millet Idli","calories":280,"protein":14,"carbs":42,"fat":5,"fiber":7,"sugar":1}', '[{"label":"Calories","change":"down","percentage":18},{"label":"Protein","change":"up","percentage":75},{"label":"Fiber","change":"up","percentage":250}]', '[{"original":"White rice","replacement":"Foxtail millet","benefit":"Higher fiber and minerals"},{"original":"Urad dal only","replacement":"Urad + moong dal","benefit":"Better amino acid profile"}]', '{"original":"Steamed","improved":"Steamed","benefit":"Already a healthy method — upgraded ingredients"}', 'Have 3-4 idlis with coconut chutney and sambar'),

-- CHINESE
('Cauliflower Fried Rice', 'Chinese', 'Dish', ARRAY['Weight Loss','Low Carb'], 'https://images.unsplash.com/photo-1543352632-5a4b24e4d2a6?w=800', '{"name":"Fried Rice","calories":520,"protein":12,"carbs":72,"fat":20,"fiber":2,"sugar":4}', '{"name":"Cauliflower Fried Rice","calories":240,"protein":16,"carbs":18,"fat":12,"fiber":6,"sugar":3}', '[{"label":"Calories","change":"down","percentage":54},{"label":"Carbs","change":"down","percentage":75},{"label":"Fiber","change":"up","percentage":200}]', '[{"original":"White rice","replacement":"Riced cauliflower","benefit":"75% fewer carbs"},{"original":"Soy sauce","replacement":"Coconut aminos","benefit":"40% less sodium"},{"original":"Vegetable oil","replacement":"Sesame oil","benefit":"Heart-healthy fats"}]', '{"original":"Stir fried in oil","improved":"Lightly sautéed","benefit":"Less oil absorption"}', 'Add tofu or chicken for extra protein'),

('Vegetable Noodle Bowl', 'Chinese', 'Dish', ARRAY['Weight Loss','Heart Healthy'], 'https://images.unsplash.com/photo-1661257711676-79a0fc533569?w=800', '{"name":"Instant Noodles","calories":380,"protein":8,"carbs":52,"fat":16,"fiber":1,"sugar":3}', '{"name":"Vegetable Noodle Bowl","calories":320,"protein":18,"carbs":38,"fat":10,"fiber":6,"sugar":2}', '[{"label":"Calories","change":"down","percentage":16},{"label":"Protein","change":"up","percentage":125},{"label":"Fiber","change":"up","percentage":500}]', '[{"original":"Instant noodles","replacement":"Whole wheat noodles","benefit":"More fiber, less sodium"},{"original":"MSG seasoning","replacement":"Fresh ginger-garlic","benefit":"No artificial additives"},{"original":"Palm oil","replacement":"Sesame oil","benefit":"Better fat profile"}]', '{"original":"Boiled with seasoning packet","improved":"Stir-fried with fresh vegetables","benefit":"More nutrients, less sodium"}', 'Load up on vegetables — aim for half the bowl'),

-- ITALIAN
('Whole Wheat Margherita', 'Italian', 'Dish', ARRAY['Heart Healthy','High Protein'], 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800', '{"name":"Pepperoni Pizza","calories":1100,"protein":28,"carbs":120,"fat":52,"fiber":4,"sugar":12}', '{"name":"Whole Wheat Margherita","calories":580,"protein":30,"carbs":62,"fat":22,"fiber":8,"sugar":6}', '[{"label":"Calories","change":"down","percentage":47},{"label":"Fat","change":"down","percentage":58},{"label":"Fiber","change":"up","percentage":100}]', '[{"original":"Refined flour base","replacement":"Whole wheat + flaxseed dough","benefit":"More fiber and omega-3"},{"original":"Mozzarella","replacement":"Part-skim mozzarella","benefit":"30% less fat"},{"original":"Pepperoni","replacement":"Grilled vegetables","benefit":"No processed meat"}]', '{"original":"Oven baked with oil","improved":"Stone baked, thin crust","benefit":"Less dough, more toppings"}', 'Two slices with a side salad is a balanced meal'),

-- MEXICAN
('Quinoa Burrito Bowl', 'Mexican', 'Dish', ARRAY['High Protein','Heart Healthy'], 'https://images.unsplash.com/photo-1623428188495-89c064ee061a?w=800', '{"name":"Beef Burrito","calories":980,"protein":38,"carbs":88,"fat":48,"fiber":6,"sugar":8}', '{"name":"Quinoa Burrito Bowl","calories":520,"protein":32,"carbs":52,"fat":18,"fiber":12,"sugar":4}', '[{"label":"Calories","change":"down","percentage":47},{"label":"Fiber","change":"up","percentage":100},{"label":"Fat","change":"down","percentage":63}]', '[{"original":"Flour tortilla","replacement":"Bowl (no wrap)","benefit":"Saves 300 calories"},{"original":"White rice","replacement":"Quinoa","benefit":"Complete protein source"},{"original":"Sour cream","replacement":"Greek yogurt","benefit":"50% less fat, more protein"}]', '{"original":"Wrapped and grilled","improved":"Assembled fresh in bowl","benefit":"No added oil from grilling tortilla"}', 'Add extra salsa for flavor without calories'),

-- MEDITERRANEAN
('Mediterranean Grain Bowl', 'Mediterranean', 'Dish', ARRAY['Heart Healthy','High Protein'], 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', '{"name":"Gyro Platter","calories":880,"protein":30,"carbs":62,"fat":52,"fiber":4,"sugar":6}', '{"name":"Mediterranean Grain Bowl","calories":480,"protein":28,"carbs":48,"fat":18,"fiber":10,"sugar":4}', '[{"label":"Calories","change":"down","percentage":45},{"label":"Fat","change":"down","percentage":65},{"label":"Fiber","change":"up","percentage":150}]', '[{"original":"Lamb gyro meat","replacement":"Grilled chicken thigh","benefit":"Less saturated fat"},{"original":"Pita bread","replacement":"Farro grains","benefit":"Ancient grain with more fiber"},{"original":"Tzatziki","replacement":"Hummus","benefit":"Plant-based protein"}]', '{"original":"Rotisserie with fat","improved":"Grilled lean","benefit":"Less rendered fat"}', 'Drizzle olive oil sparingly — a little goes a long way'),

-- JAPANESE
('Salmon Poke Bowl', 'Japanese', 'Dish', ARRAY['High Protein','Heart Healthy','Diabetic Friendly'], 'https://images.unsplash.com/photo-1633862472152-e3873eb1b3ff?w=800', '{"name":"Tempura Platter","calories":880,"protein":22,"carbs":78,"fat":52,"fiber":3,"sugar":4}', '{"name":"Salmon Poke Bowl","calories":520,"protein":38,"carbs":42,"fat":18,"fiber":6,"sugar":3}', '[{"label":"Calories","change":"down","percentage":41},{"label":"Fat","change":"down","percentage":65},{"label":"Protein","change":"up","percentage":73}]', '[{"original":"Battered tempura","replacement":"Raw sashimi-grade salmon","benefit":"No frying, rich in omega-3"},{"original":"White rice","replacement":"Brown rice + edamame","benefit":"More fiber and plant protein"},{"original":"Soy sauce","replacement":"Ponzu","benefit":"Less sodium, citrus flavor"}]', '{"original":"Deep fried","improved":"Raw / lightly seared","benefit":"Preserves omega-3 fatty acids"}', 'Half rice, half greens base for best balance'),

-- KOREAN
('Bibimbap Bowl', 'Korean', 'Dish', ARRAY['High Protein','Weight Loss'], 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800', '{"name":"Fried Bibimbap","calories":750,"protein":24,"carbs":82,"fat":34,"fiber":4,"sugar":6}', '{"name":"Healthy Bibimbap Bowl","calories":480,"protein":30,"carbs":52,"fat":16,"fiber":8,"sugar":4}', '[{"label":"Calories","change":"down","percentage":36},{"label":"Fat","change":"down","percentage":53},{"label":"Fiber","change":"up","percentage":100}]', '[{"original":"White rice","replacement":"Brown rice + barley","benefit":"More fiber and minerals"},{"original":"Fried egg","replacement":"Poached egg","benefit":"No added oil"},{"original":"Gochujang excess","replacement":"Light gochujang drizzle","benefit":"Less sugar and sodium"}]', '{"original":"Fried in stone pot","improved":"Assembled fresh","benefit":"No oil-fried rice crust"}', 'Mix everything well — the flavors combine beautifully'),

-- THAI
('Thai Basil Tofu Stir-Fry', 'Thai', 'Dish', ARRAY['Weight Loss','Heart Healthy'], 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800', '{"name":"Pad Thai","calories":720,"protein":18,"carbs":88,"fat":32,"fiber":3,"sugar":14}', '{"name":"Thai Basil Tofu Stir-Fry","calories":380,"protein":22,"carbs":28,"fat":18,"fiber":6,"sugar":5}', '[{"label":"Calories","change":"down","percentage":47},{"label":"Sugar","change":"down","percentage":64},{"label":"Fiber","change":"up","percentage":100}]', '[{"original":"Rice noodles","replacement":"Zucchini noodles","benefit":"80% fewer carbs"},{"original":"Tamarind + sugar sauce","replacement":"Fresh basil + lime","benefit":"No added sugar"},{"original":"Peanut oil","replacement":"Coconut oil spray","benefit":"Less oil overall"}]', '{"original":"High-heat wok frying","improved":"Light stir-fry","benefit":"Less oil needed with non-stick wok"}', 'Add Thai basil generously — it is calorie-free flavor'),

-- AMERICAN
('Grilled Chicken Burger', 'American', 'Dish', ARRAY['High Protein','Weight Loss'], 'https://images.unsplash.com/photo-1619221882010-23e5b72bc561?w=800', '{"name":"Double Cheeseburger & Fries","calories":1050,"protein":38,"carbs":82,"fat":62,"fiber":4,"sugar":12}', '{"name":"Grilled Chicken Burger","calories":520,"protein":42,"carbs":38,"fat":16,"fiber":6,"sugar":5}', '[{"label":"Calories","change":"down","percentage":50},{"label":"Fat","change":"down","percentage":74},{"label":"Protein","change":"up","percentage":11}]', '[{"original":"Beef patty","replacement":"Grilled chicken breast","benefit":"70% less saturated fat"},{"original":"White bun","replacement":"Whole grain bun","benefit":"More fiber"},{"original":"French fries","replacement":"Sweet potato wedges","benefit":"More vitamins, less oil"}]', '{"original":"Griddled with butter","improved":"Grilled","benefit":"No added fats"}', 'Skip the cheese or use one thin slice'),

('Avocado Toast with Eggs', 'American', 'Snack', ARRAY['Heart Healthy','Weight Loss'], 'https://images.unsplash.com/photo-1551888645-5ec881101c3f?w=800', '{"name":"Bacon & Eggs Toast","calories":600,"protein":22,"carbs":38,"fat":40,"fiber":2,"sugar":4}', '{"name":"Avocado Toast with Eggs","calories":380,"protein":18,"carbs":32,"fat":20,"fiber":8,"sugar":2}', '[{"label":"Calories","change":"down","percentage":37},{"label":"Fat","change":"down","percentage":50},{"label":"Fiber","change":"up","percentage":300}]', '[{"original":"Bacon","replacement":"Avocado","benefit":"Heart-healthy monounsaturated fats"},{"original":"White bread","replacement":"Sourdough whole grain","benefit":"Lower GI, more fiber"},{"original":"Butter","replacement":"None needed","benefit":"Avocado provides creaminess"}]', '{"original":"Fried in butter","improved":"Poached or soft-boiled","benefit":"No added fat for eggs"}', 'Half an avocado per serving is sufficient'),

-- MIDDLE EASTERN
('Falafel Wrap', 'Middle Eastern', 'Dish', ARRAY['High Protein','Heart Healthy'], 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800', '{"name":"Fried Falafel Platter","calories":780,"protein":20,"carbs":72,"fat":46,"fiber":8,"sugar":5}', '{"name":"Baked Falafel Wrap","calories":420,"protein":22,"carbs":48,"fat":16,"fiber":12,"sugar":3}', '[{"label":"Calories","change":"down","percentage":46},{"label":"Fat","change":"down","percentage":65},{"label":"Fiber","change":"up","percentage":50}]', '[{"original":"Deep fried falafel","replacement":"Oven baked falafel","benefit":"70% less oil"},{"original":"White pita","replacement":"Whole wheat wrap","benefit":"More fiber"},{"original":"Tahini drizzle","replacement":"Light tahini + lemon","benefit":"Less calorie-dense"}]', '{"original":"Deep fried","improved":"Oven baked at 200°C","benefit":"Crispy exterior without oil"}', 'Add plenty of fresh vegetables to the wrap'),

-- DESSERTS
('Berry Protein Smoothie Bowl', 'American', 'Dessert', ARRAY['Weight Loss','High Protein'], 'https://images.unsplash.com/photo-1610450620997-6921021865da?w=800', '{"name":"Ice Cream Sundae","calories":600,"protein":8,"carbs":72,"fat":32,"fiber":1,"sugar":58}', '{"name":"Berry Protein Smoothie Bowl","calories":280,"protein":22,"carbs":34,"fat":8,"fiber":6,"sugar":18}', '[{"label":"Calories","change":"down","percentage":53},{"label":"Sugar","change":"down","percentage":69},{"label":"Protein","change":"up","percentage":175}]', '[{"original":"Ice cream","replacement":"Frozen banana + protein powder","benefit":"Natural sweetness + protein"},{"original":"Chocolate sauce","replacement":"Cacao nibs","benefit":"Antioxidants without sugar"},{"original":"Whipped cream","replacement":"Greek yogurt","benefit":"Protein instead of fat"}]', '{"original":"Scooped and topped","improved":"Blended and topped","benefit":"Whole fruit retains fiber"}', 'Use seasonal berries for best flavor and nutrition'),

('Greek Yogurt Parfait', 'Mediterranean', 'Dessert', ARRAY['Diabetic Friendly','High Protein'], 'https://images.unsplash.com/photo-1571230389215-b34a89739ef1?w=800', '{"name":"Dessert Parfait","calories":480,"protein":8,"carbs":62,"fat":22,"fiber":2,"sugar":48}', '{"name":"Greek Yogurt Parfait","calories":240,"protein":20,"carbs":28,"fat":8,"fiber":4,"sugar":14}', '[{"label":"Calories","change":"down","percentage":50},{"label":"Sugar","change":"down","percentage":71},{"label":"Protein","change":"up","percentage":150}]', '[{"original":"Sweetened yogurt","replacement":"Plain Greek yogurt","benefit":"3x more protein, no added sugar"},{"original":"Granola","replacement":"Homemade oat crumble","benefit":"Less sugar and oil"},{"original":"Fruit syrup","replacement":"Fresh berries","benefit":"Natural sweetness with fiber"}]', '{"original":"Layered with sugary components","improved":"Layered with whole foods","benefit":"Each layer adds nutritional value"}', 'Use a tall glass — the layers look beautiful and control portions'),

-- BEVERAGES
('Green Protein Smoothie', 'American', 'Beverage', ARRAY['High Protein','Weight Loss'], 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800', '{"name":"Milkshake","calories":520,"protein":10,"carbs":68,"fat":24,"fiber":0,"sugar":62}', '{"name":"Green Protein Smoothie","calories":220,"protein":24,"carbs":22,"fat":6,"fiber":5,"sugar":12}', '[{"label":"Calories","change":"down","percentage":58},{"label":"Sugar","change":"down","percentage":81},{"label":"Protein","change":"up","percentage":140}]', '[{"original":"Ice cream base","replacement":"Frozen banana + spinach","benefit":"Natural sweetness + iron"},{"original":"Whole milk","replacement":"Almond milk","benefit":"80% fewer calories"},{"original":"Sugar syrup","replacement":"Dates","benefit":"Natural fiber-rich sweetener"}]', '{"original":"Blended with ice cream","improved":"Blended with whole foods","benefit":"No processed ingredients"}', 'Add a tablespoon of chia seeds for omega-3'),

('Masala Chai (Healthy)', 'North Indian', 'Beverage', ARRAY['Heart Healthy','Diabetic Friendly'], 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=800', '{"name":"Regular Masala Chai","calories":180,"protein":4,"carbs":28,"fat":6,"fiber":0,"sugar":22}', '{"name":"Healthy Masala Chai","calories":80,"protein":6,"carbs":10,"fat":3,"fiber":1,"sugar":4}', '[{"label":"Calories","change":"down","percentage":56},{"label":"Sugar","change":"down","percentage":82},{"label":"Protein","change":"up","percentage":50}]', '[{"original":"Full cream milk","replacement":"Oat milk","benefit":"Less saturated fat"},{"original":"3 tsp sugar","replacement":"Half tsp jaggery","benefit":"Minerals + much less sugar"},{"original":"Pre-mixed powder","replacement":"Fresh spices","benefit":"No artificial flavors"}]', '{"original":"Boiled with sugar","improved":"Simmered with fresh spices","benefit":"Better spice extraction, less sugar"}', 'Enjoy without biscuits — the spices are satisfying on their own'),

-- MORE SNACKS
('Overnight Oats', 'American', 'Snack', ARRAY['Heart Healthy','Diabetic Friendly'], 'https://images.unsplash.com/photo-1665394055917-de22650a17b4?w=800', '{"name":"Sugary Cereal","calories":500,"protein":6,"carbs":82,"fat":12,"fiber":2,"sugar":38}', '{"name":"Overnight Oats Bowl","calories":320,"protein":14,"carbs":42,"fat":10,"fiber":8,"sugar":10}', '[{"label":"Calories","change":"down","percentage":36},{"label":"Sugar","change":"down","percentage":74},{"label":"Fiber","change":"up","percentage":300}]', '[{"original":"Refined cereal","replacement":"Rolled oats","benefit":"Whole grain, slow-release energy"},{"original":"Added sugar","replacement":"Honey + cinnamon","benefit":"Natural sweetness with antioxidants"},{"original":"Regular milk","replacement":"Almond milk + chia","benefit":"Omega-3 and fewer calories"}]', '{"original":"Pour and eat","improved":"Soaked overnight","benefit":"Better digestibility, creamy texture"}', 'Prep the night before — grab and go in the morning');
